language: ruby
rvm:
- 2.1.1
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
env:
  global:
  - secure: d1XBQWSijlbBTJnCm5DKs8kD7AC7UGVsWkn5gaPNdj6/aHnKoizwgk8eDIrwtmWh2yQMkxVv6Qqpj/wB/wuJSglY8FskMTzwcUIj9BN2XpC5CKz0QwVEhwg5RZYXWsjXXgcf3+VGFF+1bNXl+HAIm/bbDIfnavQSAVHOADmrSAE=
  - secure: aKXj7uIUNI7TFTXS2XTAd4OXCegCp2CunyYF1L3lzBxxj/piuO6ZSmuemnWm6BnepKugu5HCqiRgSDlYjgMZot3yE30I/SW0MQSlFj7qBAn64c3QedONfoVpwVd7RfLYBxzp7vwVvKsPsHWIIuUFieVCicxQCHpOKjdyWhCOqr0=
  - secure: OXTHgTX+E7GKc4s/X6YpOELo9w7IAllderwbuw34EUe884DjHtJYQrui/S+yaHUWvvrFOJ09Lz5kMEZDUT654SXqOiF3rqINuEAZhJav5MeDoE1szGvBxeBtdwpqovlfv1srZZPw3hykO3OD41Pdms3sEKL9wDRUwXybMSob2CE=
