# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink: 				/:categories/:title
post_dirs: 				false

# Setup
title:            userinterfac.es
tagline:          'Be inspired by in-depth analysis of great UI'
description:      'In-depth analysis of example great interfaces to help inspire you.'
authors:   				'Curated by <a href="https://twitter.com/rossbeale" target="_blank">@rossbeale</a>, <a href="https://twitter.com/piefoundry" target="_blank">@piefoundry</a> &amp; <a href="https://twitter.com/stevy_smith" target="_blank">@stevy_smith</a>.'
url:              http://userinterfac.es

author:
  name:           'Ross Beale'
  url:            https://twitter.com/rossbeale

paginate:         5
paginate_path: 		":num"

excerpt_separator: <!-- more -->

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/rossbeale/userinterfac.es

sitemap:
    file: 				'/sitemap.xml'
    exclude:
    - '/atom.xml'
    include_posts:
    - '/index.html'
    change_frequency_name: "change_frequency"
    priority_name: "priority"