title:        Hyde
tagline:      "Hyde, a Jekyll theme"
url:          http://andhyde.com
version:      1.0.0
author:
  name:       ""
  email:      ""
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     5
